In [ ]:
import pandas as pd
import numpy as np

In [1]:
df=pd.read_csv('/home/comp-proj-44/Downloads/archive/iris.csv')

NameError: name 'pd' is not defined

In [ ]:
df['species']=df['species'].map({'setosa':0,'virginica':1, 'versicolor':2})

NameError: name 'df' is not defined

In [ ]:
df.dtypes

NameError: name 'df' is not defined

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.054000      3.758667     1.198667    1.000000
std        0.828066     0.433594      1.764420     0.763161    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [ ]:
df.shape

(150, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [ ]:
df.min()

sepal_length    4.3
sepal_width     2.0
petal_length    1.0
petal_width     0.1
species         0.0
dtype: float64

In [ ]:
df.max()

sepal_length    7.9
sepal_width     4.4
petal_length    6.9
petal_width     2.5
species         2.0
dtype: float64

In [ ]:
df.mean()

sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
species         1.000000
dtype: float64

In [ ]:
df.median()

sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
species         1.00
dtype: float64

In [ ]:
df.mode()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.0          3.0           1.5          0.2        0
1           NaN          NaN           NaN          NaN        1
2           NaN          NaN           NaN          NaN        2

In [ ]:
df.std()

sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
species         0.819232
dtype: float64

In [ ]:
df.groupby('species')['sepal_length'].agg(['mean','median','min','max','std'])

          mean  median  min  max       std
species
0        5.006     5.0  4.3  5.8  0.352490
1        6.588     6.5  4.9  7.9  0.635880
2        5.936     5.9  4.9  7.0  0.516171

In [ ]:
df2=pd.read_csv('/home/comp-proj-44/Downloads/archive/iris.csv')

In [ ]:
def stats_summry(data):
    return{
        'Mean':data.mean(),
        'STD dev': data.std(),
        '25th percentile':data.quantile(0.25),
        '50th percentile':data.quantile(0.5),
        '75th percentile':data.quantile(0.75)
    }
for sp in df2['species'].unique():
    print('\n stats for',sp)
    print(stats_summry(df2[df['species']==sp]['petal_length']))

 stats for setosa
{'Mean': nan, 'STD dev': nan, '25th percentile': np.float64(nan), '50th percentile': np.float64(nan), '75th percentile': np.float64(nan)}

 stats for versicolor
{'Mean': nan, 'STD dev': nan, '25th percentile': np.float64(nan), '50th percentile': np.float64(nan), '75th percentile': np.float64(nan)}

 stats for virginica
{'Mean': nan, 'STD dev': nan, '25th percentile': np.float64(nan), '50th percentile': np.float64(nan), '75th percentile': np.float64(nan)}

In [ ]:
df.var()

sepal_length    0.685694
sepal_width     0.188004
petal_length    3.113179
petal_width     0.582414
species         0.671141
dtype: float64

In [ ]:
df[['species',]].groupby(speci).mean()